theme: jekyll-theme-cayman
title: [The title of your site]
description: [A short description of your site's purpose]
logo: https://raw.githubusercontent.com/mehrshaddarzi/wp-cli-reference-command/master/screenshot-1.jpg
show_downloads: true
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
