theme: jekyll-theme-cayman
title: Backup and Restore WordPress in Google Drive service
description: Google Drive Command for WP-CLI
logo: ''
show_downloads: true
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
